### PR TITLE
Update securitypolicy.go

### PR DESCRIPTION
**Pull request by judavi**
Following the convention of the other fields, this field should be maximumFixUnavailableSeverity. Also following the documentation from here [resources.md](https://github.com/grafeas/kritis/blob/71a1d2c56f1549e2e15512058e961ab932b8de85/docs/resources.md) the field should be maximumFixUnavailableSeverity

### CODE REVIEW

**Comment by judavi** [comment]
This difference on the name field is related to https://github.com/grafeas/kritis/issues/458

**Comment by ooq** [comment]
A good to have: Do you think we can add some integration tests to catch this? Thanks.

**Comment by aysylu** [comment]
@judavi: could you please clarify if this is fixing an existing bug or is a documentation/naming consistency fix?

**Comment by judavi** [comment]
@aysylu I'll say both?
- Documentation consistency :
https://github.com/grafeas/kritis/blob/71a1d2c56f1549e2e15512058e961ab932b8de85/docs/resources.md
Captura de Pantalla 2020-01-30 a la(s) 7 57 58 a  m

- And struct consistency/bug? because in the structs the all the fields/values has the same name in camel case, but this one, in particular, is not following the convention:
Captura de Pantalla 2020-01-30 a la(s) 7 59 34 a  m

So because of that, I was struggling a little bit to verify if the image vulnerabilities policy was working correctly or not.

By the way @ooq I'll be happy to add the integration test. But, could you guide me where these tests should be added? and a brief idea of how what we should be testing? I mean, name conventions? or a particular test for MaximumFixUnavailableSeverity?

**Comment by ooq** [comment]
Hi @judavi , thanks for the explanation!
The integration tests are all here: https://github.com/grafeas/kritis/blob/master/integration/run_test.go
The existing tests unfortunately does not test this field, so it will be good to add that.

It is strange given that the ISP yaml in integration test is already using the correct field name. 
https://github.com/grafeas/kritis/blob/6b52ba2b6aa78b8fe087df8c8c16fa667405f0f9/integration/testdata/image-security-policy/my-isp.yaml#L13

**Comment by ooq** [comment]
@aysylu Do you know why kokoro test is not triggered on this PR?

**Comment by aysylu** [comment]
@judavi: thanks for clarifying! Sounds good and we appreciate your thorough investigation and the fix in this PR. I'll let @ooq guide you through adding the integration tests. Thanks for your active contribution to Grafeas and Kritis!

**Comment by aysylu** [comment]
@ooq: for posterity, you'll want to add `kokoro:run` label to run integration tests.

**Comment by ooq** [comment]
Update: i'll merge this PR once tests pass.

**Comment by ba32107** [comment]
Hello, we just ran into this problem ourselves and it took us quite a while to investigate the root cause. Just bumping on this PR to have it merged, because I believe currently, if someone sets up an `ImageSecurityPolicy` according to the docs, it will simply not work due to this issue.

**Comment by ooq** [comment]
@ba32107 This PR was approved but pending on some test issues. Let me see if I can fix it and get it merged in. Thanks for the feedback!

**Comment by ooq** [comment]
It looks like [image-security-policy-crd.yaml](https://github.com/grafeas/kritis/blob/faeba81c520ca742fe378cc87d99e04bdda098c1/artifacts/image-security-policy-crd.yaml#L26) would also needs to be updated accordingly.

**Comment by ooq** [comment]
Merged. Thanks for the PR @judavi !

**Pull request merged**
