### PR TITLE
Use go modules

### PR DESCRIPTION
**Pull request by cjones-shopify**
Dep has been deprecated as of September https://github.com/golang/go/issues/38158#issuecomment-689099575 2020. This PR removes `dep` and switches the project to use Go modules.

### CODE REVIEW

**Comment by ooq** [comment]
Thanks for cleaning this up! Can you fix the travis test, I think it's complaining because some vendor script is missing after the update: https://travis-ci.org/github/grafeas/kritis/builds/747482496

**Comment by ooq** [comment]
Looks like it's still failing :( @cjones-shopify

**Comment by cjones-shopify** [comment]
The Travis-CI pipeline takes quite a long time to run, I'm sorry it's taken so long for me to fix this PR! :<

**Comment by ooq** [comment]
No worries, @cjones-shopify! I've recently noticed that Travis might not pass back the build status back -- not sure why. I'll check when this rerun finishes.

**Comment by ooq** [comment]
Looks like it's being queued forever :(

**Comment by ooq** [comment]
Hi just a quick update that the travis issue seems common due to their migration phase from `travis-ci.org` to `travis-ci.com`. I just fixed it by completing the migration.
The test looks good now (the `Travis CI - Pull Request` check) and you can ignore  the `continuous-integration/travis-ci/pr` check.
Sorry for the confusion!

**Review by ooq — APPROVED** [review]

**Comment by cjones-shopify** [comment]
Thank you so much @ooq!

**Pull request merged**
