### PR TITLE
Update templates to allow installing kritis in a different namespace

### PR DESCRIPTION
**Pull request by priyawadhwa**
Updated templates and the install README

### CODE REVIEW

**Comment by aaron-prindle** [comment]
to allow for integration tests to be namespaced we also need to reuse the csr somehow

**Comment by aaron-prindle** [comment]
or disable the pre-install hooks

**Comment by priyawadhwa** [comment]
I added a `--delete-csr` flag in #130, we can set it to false in the integration tests so that the same CSR is used every time.

**Comment by priyawadhwa** [comment]
Oh, but I think we'll need to add the flag to the preinstall pod template for it to work!

**Pull request merged**
