### PR TITLE
Update to k8s v1.18

### PR DESCRIPTION
**Pull request by cjones-shopify**
This PR updates Kritis to work with Kubernetes v1.18.

### CODE REVIEW

**Comment by cjones-shopify** [comment]
Hey @ooq, do you know what's up with the Cloud Build run? I can't see the output of it unfortunately.

**Comment by ooq** [comment]
@cjones-shopify  Opened #599 to fix the Cloud Build issue, I'll also look into getting your access.

**Comment by cjones-shopify** [comment]
Thank you!

**Comment by ooq** [comment]
@cjones-shopify all checks are green now.

**Review by Nilay-Shah — APPROVED** [review]

**Comment by cjones-shopify** [comment]
Whoops, shouldn't have clicked that button! I'll rebase locally!

**Comment by cjones-shopify** [comment]
@googlebot I fixed it.

**Comment by cjones-shopify** [comment]
@ooq would you be able to confirm what's broken in the GCB pipeline?

**Comment by ooq** [comment]
@cjones-shopify The signer tests failed because vulnerability info for an image is updated. I'll push a fix (a temporary one first).

**Comment by ooq** [comment]
https://github.com/grafeas/kritis/pull/603 would address it.

**Review by ooq — APPROVED** [review]

**Pull request merged**
