### PR TITLE
Fix minor variable name error in admission go.

### PR DESCRIPTION
**Pull request by ooq**

### CODE REVIEW

**Comment by aysylu** [comment]
Just waiting for kokoro to finish, then I'll merge.

**Comment by ooq** [comment]
@aysylu Yes the local integration passed as I just verified. (sorry for the delay I had some issue with running the tests.) I'll merge this for now.

**Comment by ooq** [comment]
The tests passed. Triggering a re-test due to outdated branch.

**Comment by ooq** [comment]
Checks passed. Merging this.

**Pull request merged**
