### PR TITLE
Fix a logic bug in the GenericAttestationPolicy review.

### PR DESCRIPTION
**Pull request by nenaddedic**
Currently intended semantics is disjunctive: an image passes policy
checks if at least one GAP is satisfied, which in turn is if at least
one AttestationAuthority verifies the signature.

### CODE REVIEW

**Comment by aysylu** [comment]
Kokoro test failure is due to an intermittent timeout, unrelated to this PR. I'll re-run it once the branch is synced with HEAD and the minor comments are addressed.

**Comment by steakunderscore** [comment]
What's the design decision for this? Reading the ticket I assume this was discussed internally, perhaps exposing some of that communication would be useful.

We currently make use of Binauth's `requireAttestationsBy` where we require 3 attestors to be satisfied before we allow images to be admitted. With this change, is there a way that an admission can require multiple attestors?

For context, from the binauth [policy ref]:
> `requireAttestationsBy` specifies one or more attestors who must authorize the release before a container image can be deployed.

Let me know if this would be better discussed somewhere else. I can't find the Kritis Google Group, only the Google Groups for Grafeas.

[policy ref]: https://cloud.google.com/binary-authorization/docs/policy-yaml-reference

**Comment by nenaddedic** [comment]
Henry, yes, this ended up more confusing than necessary, sorry about that!

First, some reassurance: As indicated in this post
<https://groups.google.com/forum/#!topic/kritis-users/ydZkjo39n-c> (btw
that's the Kritis Google Group), our plan is to implement the semantics
which you want -- ALL attestors required.

Second, Kritis does not currently implement the Binary Auth semantics,
instead it wants ANY attestor.  I had introduced a bug where I accidentally
changed that to ALL attestors.

Third, this PR restores the previous ANY attestor semantics, with full
awareness that this is changing soon.  The change to ALL attestors is going
to be part of a "package" of changes (see referenced post), so we don't
want to sneak it in and break backwards compatibility unannounced.

We realize that the discrepancy between Binary Auth semantics and Kritis
semantics is confusing, and are actively working on fixing that.  Thanks
for your understanding and, as always, PRs are welcome :)

**Comment by aysylu** [comment]
@nenaddedic: +1 to what you said, thanks for the clarifications!

@steakunderscore: I just realized the group's visiblity settings made it available only to the group's members. Now fixed: https://groups.google.com/forum/#!forum/kritis-users. Please feel free to join!

**Comment by aysylu** [comment]
I'm addressing the kokoro test failure and looking into it separately, as it's not caused by this PR.

**Pull request merged**
