### PR TITLE
Update helm chart to make it stable and safer

### PR DESCRIPTION
**Pull request by dragon3**
## WHAT
This pull request changes the followings regarding to the helm chart:
- Use jobs for helm hooks instead of pods to ensure the order.
- Fix and cleanup hook-delete-policy.
- Update version and fix description in Chart.yaml.

## WHY
This pull request fixes 2 issues I got in the current helm chart.
In addition, I found the description in Chart.yaml was incorrect. This pull request fix it as well.

### `cluster-admin` service account remains after installation
The helm chart creates a service account which has `cluster-admin` in pre-install hook. I understand it's necessary to approve TLS certificate for the validating admission webhook. But it should be removed as soon as possible, otherwise it might be a security risk because of the strong role.

### `helm install` failed randomly
I got `helm install` failed randomly. It worked some time, at other times didn't.

I thought it's because it uses Pod for the helm hooks, probably `WaitForPodComplete`.

Instead using Job seems more reliable to ensure the execution order because many charts in https://github.com/helm/charts use Job for hooks.

### CODE REVIEW

**Comment by tejal29** [comment]
Thanks for the PR. I just added the kokoro:run label and hopefully it will be picked up the integration tests.

**Comment by dragon3** [comment]
@tejal29 
Thank you for the comment. 
Could you let me know the reason why the `kokoro` build is failed?

Thank you!

**Comment by tejal29** [comment]
Sorry, i ran the int tests twice. And both times, it errored out due to
```
--- FAIL: TestKritisCron (316.82s)
	run_test.go:448: setup: deleting stray webhook: kritis-validation-hook-500f1475
	run_test.go:448: setup: deleting stray webhook: kritis-validation-hook-deployments-500f1475
	run_test.go:448: setup: installing kritis with image version b676b7f0b1cfe1039eada02e380a26597a4afb24 in namespace e8b6ec99...
	run_test.go:448: install: postinstall pod didn't complete: timed out waiting for the condition
FAIL
FAIL	github.com/grafeas/kritis/integration	654.737s
Makefile:137: recipe for target 'integration-prod' failed
make: *** [integration-prod] Error 1
make: *** [integration-in-docker] Error 2


[ID: 7246066] Build finished after 999 secs, exit value: 2


Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
[15:22:13] Collecting build artifacts from build VM
Build script failed with exit code: 2[15:22:22] /tmp/workspace/workspace/runtimes-common/kritis/presubmit/artifacts/custom_sponge_config.csv does not exist in the workspace, no custom config value to log

```

**Comment by aysylu** [comment]
Hi @dragon3, are you still interested in contributing this? If so, happy to work together to figure out how to get this merged.

**Comment by dragon3** [comment]
@aysylu 
I'm so sorry for late reply... This pull request is outdated, so let me close it.

Thank you for your help 🙏

**Comment by aysylu** [comment]
@dragon3 no problem and thanks for the update!

**Pull request closed without merging**
